# Generated by Django 5.2.9 on 2026-05-26 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('grade', models.IntegerField(choices=[(1, '1-sinf'), (2, '2-sinf'), (3, '3-sinf'), (4, '4-sinf'), (5, '5-sinf'), (6, '6-sinf'), (7, '7-sinf'), (8, '8-sinf'), (9, '9-sinf'), (10, '10-sinf'), (11, '11-sinf')])),
                ('barcode', models.CharField(max_length=14, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=200)),
                ('fcm_token', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChildDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_model', models.CharField(blank=True, max_length=100)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('battery_level', models.IntegerField(default=0)),
                ('is_online', models.BooleanField(default=False)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device', to='children.child')),
            ],
        ),
    ]
